### ISSUE TITLE
Version controlling / ignoring modified config files

### ISSUE THREAD

**Issue by simongamester** [RippleOSI/Helm-PHR-Generator#9]
I can see that the generator modifies config files within the Core project. Is there a risk that these modified files are accidentally committed to the Core repository? Should we set up ignore rules to ensure these are excluded?

**Comment by BogdanScherban** [comment]
@simongamester 

Config files in Core-version shouldn't be added to ignore. 
Because in some cases we update this files. For example, when we update the Core for possibility to add new non-core plugins automatically.

Why we can minimize the risk?
We have unit-tests, and before pushing new changes we usually should run the command 
**npm run test-update**

And we should always look attentively at our changes. It is impossible to commit and push files without 
preliminary reviewing.

**Comment by simongamester** [comment]
Ok, thanks. Think we can leave for now.
